/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FusioRegistry {
  export type ReceiptRecordStruct = {
    receiptId: BytesLike;
    jobId: BytesLike;
    agentId: BytesLike;
    workerIdHash: BytesLike;
    jobHash: BytesLike;
    completedAt: BigNumberish;
    outcome: BigNumberish;
    costAgr: BigNumberish;
  };

  export type ReceiptRecordStructOutput = [
    receiptId: string,
    jobId: string,
    agentId: string,
    workerIdHash: string,
    jobHash: string,
    completedAt: bigint,
    outcome: bigint,
    costAgr: bigint
  ] & {
    receiptId: string;
    jobId: string;
    agentId: string;
    workerIdHash: string;
    jobHash: string;
    completedAt: bigint;
    outcome: bigint;
    costAgr: bigint;
  };
}

export interface FusioRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "deactivateAgent"
      | "getReceipt"
      | "isRegistered"
      | "orchestrator"
      | "owner"
      | "receipts"
      | "registerAgent"
      | "renounceOwnership"
      | "setOrchestrator"
      | "transferOwnership"
      | "writeReceipt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "OwnershipTransferred"
      | "ReceiptWritten"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "orchestrator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "receipts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOrchestrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeReceipt",
    values: [FusioRegistry.ReceiptRecordStruct]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeReceipt",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentId: BytesLike];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agentId: BytesLike, wallet: AddressLike];
  export type OutputTuple = [agentId: string, wallet: string];
  export interface OutputObject {
    agentId: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptWrittenEvent {
  export type InputTuple = [receiptId: BytesLike, jobId: BytesLike];
  export type OutputTuple = [receiptId: string, jobId: string];
  export interface OutputObject {
    receiptId: string;
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FusioRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FusioRegistry;
  waitForDeployment(): Promise<this>;

  interface: FusioRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        agentId: string;
        wallet: string;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  deactivateAgent: TypedContractMethod<
    [agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getReceipt: TypedContractMethod<
    [receiptId: BytesLike],
    [FusioRegistry.ReceiptRecordStructOutput],
    "view"
  >;

  isRegistered: TypedContractMethod<[agentId: BytesLike], [boolean], "view">;

  orchestrator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  receipts: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        receiptId: string;
        jobId: string;
        agentId: string;
        workerIdHash: string;
        jobHash: string;
        completedAt: bigint;
        outcome: bigint;
        costAgr: bigint;
      }
    ],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [agentId: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOrchestrator: TypedContractMethod<
    [_orchestrator: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  writeReceipt: TypedContractMethod<
    [receipt: FusioRegistry.ReceiptRecordStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        agentId: string;
        wallet: string;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [receiptId: BytesLike],
    [FusioRegistry.ReceiptRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[agentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "orchestrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        receiptId: string;
        jobId: string;
        agentId: string;
        workerIdHash: string;
        jobHash: string;
        completedAt: bigint;
        outcome: bigint;
        costAgr: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentId: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOrchestrator"
  ): TypedContractMethod<[_orchestrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "writeReceipt"
  ): TypedContractMethod<
    [receipt: FusioRegistry.ReceiptRecordStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptWritten"
  ): TypedContractEvent<
    ReceiptWrittenEvent.InputTuple,
    ReceiptWrittenEvent.OutputTuple,
    ReceiptWrittenEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(bytes32)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(bytes32,address)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReceiptWritten(bytes32,bytes32)": TypedContractEvent<
      ReceiptWrittenEvent.InputTuple,
      ReceiptWrittenEvent.OutputTuple,
      ReceiptWrittenEvent.OutputObject
    >;
    ReceiptWritten: TypedContractEvent<
      ReceiptWrittenEvent.InputTuple,
      ReceiptWrittenEvent.OutputTuple,
      ReceiptWrittenEvent.OutputObject
    >;
  };
}
