/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FusioEscrow {
  export type EscrowJobStruct = {
    jobId: BytesLike;
    requester: AddressLike;
    worker: AddressLike;
    amount: BigNumberish;
    startedAt: BigNumberish;
    completedAt: BigNumberish;
    status: BigNumberish;
    faultClass: BigNumberish;
    receiptHash: BytesLike;
  };

  export type EscrowJobStructOutput = [
    jobId: string,
    requester: string,
    worker: string,
    amount: bigint,
    startedAt: bigint,
    completedAt: bigint,
    status: bigint,
    faultClass: bigint,
    receiptHash: string
  ] & {
    jobId: string;
    requester: string;
    worker: string;
    amount: bigint;
    startedAt: bigint;
    completedAt: bigint;
    status: bigint;
    faultClass: bigint;
    receiptHash: string;
  };
}

export interface FusioEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getJob"
      | "getJobStatus"
      | "jobs"
      | "lockEscrow"
      | "orchestrator"
      | "owner"
      | "releaseEscrow"
      | "renounceOwnership"
      | "returnEscrow"
      | "setOrchestrator"
      | "token"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowLocked"
      | "EscrowReleased"
      | "EscrowReturned"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getJobStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "lockEscrow",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orchestrator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseEscrow",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnEscrow",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrchestrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace EscrowLockedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    requester: AddressLike,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    requester: string,
    worker: string,
    amount: bigint
  ];
  export interface OutputObject {
    jobId: string;
    requester: string;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    worker: AddressLike,
    amount: BigNumberish,
    receiptHash: BytesLike
  ];
  export type OutputTuple = [
    jobId: string,
    worker: string,
    amount: bigint,
    receiptHash: string
  ];
  export interface OutputObject {
    jobId: string;
    worker: string;
    amount: bigint;
    receiptHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReturnedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    requester: AddressLike,
    amount: BigNumberish,
    faultClass: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    requester: string,
    amount: bigint,
    faultClass: bigint
  ];
  export interface OutputObject {
    jobId: string;
    requester: string;
    amount: bigint;
    faultClass: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FusioEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FusioEscrow;
  waitForDeployment(): Promise<this>;

  interface: FusioEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getJob: TypedContractMethod<
    [jobId: BytesLike],
    [FusioEscrow.EscrowJobStructOutput],
    "view"
  >;

  getJobStatus: TypedContractMethod<[jobId: BytesLike], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        jobId: string;
        requester: string;
        worker: string;
        amount: bigint;
        startedAt: bigint;
        completedAt: bigint;
        status: bigint;
        faultClass: bigint;
        receiptHash: string;
      }
    ],
    "view"
  >;

  lockEscrow: TypedContractMethod<
    [jobId: BytesLike, worker: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  orchestrator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  releaseEscrow: TypedContractMethod<
    [jobId: BytesLike, receiptHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  returnEscrow: TypedContractMethod<
    [jobId: BytesLike, faultClass: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOrchestrator: TypedContractMethod<
    [_orchestrator: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [FusioEscrow.EscrowJobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobStatus"
  ): TypedContractMethod<[jobId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        jobId: string;
        requester: string;
        worker: string;
        amount: bigint;
        startedAt: bigint;
        completedAt: bigint;
        status: bigint;
        faultClass: bigint;
        receiptHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockEscrow"
  ): TypedContractMethod<
    [jobId: BytesLike, worker: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "orchestrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseEscrow"
  ): TypedContractMethod<
    [jobId: BytesLike, receiptHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnEscrow"
  ): TypedContractMethod<
    [jobId: BytesLike, faultClass: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrchestrator"
  ): TypedContractMethod<[_orchestrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EscrowLocked"
  ): TypedContractEvent<
    EscrowLockedEvent.InputTuple,
    EscrowLockedEvent.OutputTuple,
    EscrowLockedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReturned"
  ): TypedContractEvent<
    EscrowReturnedEvent.InputTuple,
    EscrowReturnedEvent.OutputTuple,
    EscrowReturnedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "EscrowLocked(bytes32,address,address,uint256)": TypedContractEvent<
      EscrowLockedEvent.InputTuple,
      EscrowLockedEvent.OutputTuple,
      EscrowLockedEvent.OutputObject
    >;
    EscrowLocked: TypedContractEvent<
      EscrowLockedEvent.InputTuple,
      EscrowLockedEvent.OutputTuple,
      EscrowLockedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,address,uint256,bytes32)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "EscrowReturned(bytes32,address,uint256,uint8)": TypedContractEvent<
      EscrowReturnedEvent.InputTuple,
      EscrowReturnedEvent.OutputTuple,
      EscrowReturnedEvent.OutputObject
    >;
    EscrowReturned: TypedContractEvent<
      EscrowReturnedEvent.InputTuple,
      EscrowReturnedEvent.OutputTuple,
      EscrowReturnedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
